---
- name: Uninstall old docker versions
  ansible.builtin.package:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
  when: container_package_name == 'docker-ce'

- name: Allow apt to use a repository over https (debian)
  ansible.builtin.package:
    name: ['apt-transport-https', 'ca-certificates', 'gnupg', 'software-properties-common']
    update_cache: true
  register: result
  until: result is succeeded

- name: Add docker repository
  ansible.builtin.deb822_repository:
    architectures: "{{ ceph_architecture_mapping.get(ansible_facts['architecture']) }}"
    name: docker-ce
    components: stable
    enabled: true
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    state: present
    suites: "{{ ansible_facts['distribution_release'] }}"
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
  when: container_package_name == 'docker-ce'
