---
galaxy_info:
  company: Red Hat
  author: ceph-ansible contributors
  description: Installs CephFS Mirror daemon
  license: Apache
  min_ansible_version: '2.7'
  platforms:
    - name: EL
      versions:
        - 'all'
  galaxy_tags:
    - system
dependencies: []
