---
- name: Restart ceph cephfs mirrors
  ansible.builtin.systemd:
    name: "{{ 'ceph-cephfs-mirror@' + ceph_cephfs_mirror_daemon_id if containerized_deployment | bool else 'cephfs-mirror@' + ceph_cephfs_mirror_daemon_id }}"
    state: restarted
    daemon_reload: true
