---
- name: Include_tasks systemd.yml
  ansible.builtin.include_tasks: systemd.yml

- name: Systemd start cephfs mirror container
  ansible.builtin.systemd:
    name: ceph-cephfs-mirror@{{ ceph_cephfs_mirror_daemon_id }}
    state: started
    enabled: true
    masked: false
    daemon_reload: true
